services:
  db:
      image: mysql:8-debian
      restart: always
      volumes:
          - ../.mysql:/var/lib/mysql
      ports:
        - 3308:3306
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: snake-leaderboard
  api:
      image: mkluszczynski/snake-leaderboard
      restart: always
      network_mode: host
