on:
  push:
    branches: ["main", "feat/*"]
  pull_request:
    branches: ["main", "feat/*"]
jobs:
  test: 
    name: Run unit test and e2e tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20.14
      - name: Install dependencies
        run: npm i
      - name: Run unit tests
        run: npm run test
      - name: Run e2e tests
        run: npm run test:e2e
        
        
