on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  test: 
    name: Run unit tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Use nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20.14
          
      - name: Copy .env
        run: cp .env.dev .env
        
      - name: Install dependencies
        run: npm i
        
      - name: Run unit tests
        run: npm run test
        
